### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by jgosmann** [tcstewar/pytry#1]
PyPI lists pytry under Python 3, but there is at least on non-function style print statement:
```python
Traceback (most recent call last):
  File "/home/jgosmann/.virtualenvs/kajic-frontiers2016/bin/pytry", line 7, in <module>
    from pytry.cmdline import run
  File "/home/jgosmann/.virtualenvs/kajic-frontiers2016/lib/python3.5/site-packages/pytry/cmdline.py", line 30
    print 'Error: no pytry.Trial class found in %s' % filename
                                                  ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by tcstewar** [comment]
Argh -- I really need to learn to put a `from __future__ import print_function` at the top of files like that... especially when this file isn't tested at the moment.

I just put in commit 62208f161c29968235d9d0a61bbd12242637261d that should fix this.  Thank you!

**Comment by tcstewar** [comment]
Argh, the way I fixed it enforces print_function for _all_ pytry.Trial objects...  that's not quite what I wanted...  lemme fix that fix....

**Comment by tcstewar** [comment]
All better now...  :)
