### ISSUE TITLE
Not closing simulator causes GPU memory error 

### ISSUE THREAD

**Issue by ikajic** [tcstewar/pytry#11]
When running a large amount of simulations (I do it with nengo_ocl) without closing the simulator explicitly, or without using:

```python
with sim:
    sim.run(p.sim_len)
```

the GPU memory gets eaten up ending up with the following error:
`pyopencl.cffi_cl.MemoryError: clenqueuewritebuffer failed: MEM_OBJECT_ALLOCATION_FAILURE`

**Comment by tcstewar** [comment]
Argh!  Thank you for finding that...  It should now be fixed with https://github.com/tcstewar/pytry/commit/47e385fb4568d50893fe85b0b3dc01701421bd30
