### ISSUE TITLE
Should provide programatic access to parameter parsing

### ISSUE THREAD

**Issue by jgosmann** [tcstewar/pytry#4]
At the moment there seems to be no way to parse command line arguments and pass them to the model except by doing it manually or using the `pytry` command (and there might be reason not to use it, for example it is not working with Python 3 at the moment, see #1)

**Comment by tcstewar** [comment]
Interesting....  I actually purposefully separated that out in pytry, as opposed to what I did in ctn_benchmarks.  In ctn_benchmarks, when you called run() without any arguments, then it would check the command line for arguments, but if you called `run(param1=whatever, ...)` then it would ignore the arguments.  I always felt uncomfortable with this slightly weird behaviour, and so I thought I'd try it this way where the command line stuff is completely separate.

Now that I've fixed #1, would it still be useful to be able to parse from the command line programmatically?  What should the syntax be for calling it?

**Comment by jgosmann** [comment]
Yes, I think it would still be useful and that it is possible to do it in a consistent way. For example something like:

``` python
params = pytry.parse_args(sys.argv)
trial.run(**params)
```

That would make things more reusable. For example one could add the pytry invocation to the end of their script (so it doesn't need to be called with pytry), it would make it easier to use pytry within a Python package (where it can be hard to figure out the path that needs to be passed to pytry), or add some custom handling of command line arguments.

**Comment by tcstewar** [comment]
oooo....  I like the idea of having to manually pass in `sys.argv`.  However, it'd have to be something like this:

```
params = trial.parse_args(sys.argv)
trial.run(**params)
```

I could also see doing this:

```
trial.run_with_parsed_args(sys.argv)
```

Do you have any preferences there?

**Comment by jgosmann** [comment]
I probably would default to `sys.argv`, but that can be debated and I wouldn't be too unhappy if it has to be passed in manually. (Maybe safer for now as it is easier to introduce a default than to eliminate it.)

I prefer the first option because it gives more modularity. I can still do stuff with the parsed args to adjust them or just parse the args without running anything.

**Comment by tcstewar** [comment]
I'm looking at it in more detail now, and I think I could do

```
params = trial.parse_args()
trial.run(**params)
```

where the default passed into parse_args is the same default that is passed in to `optparse.OptionParser.parse_args`, which is actually `sys.argv[1:]`.  That keeps it consistent with the python package, and provides the modularity.

**Comment by tcstewar** [comment]
This is now in master. fc9dc532878750b366a6c01c45345862f1ad2228  :)  And, as a bonus, this let me add some tests to the parser!

**Comment by jgosmann** [comment]
> this let me add some tests to the parser!

That's why test-driven development can be a good idea. It forces you to be modular.

> This is now in master

Nice, but will there be a PyPI release soon? Otherwise, it won't help me a lot yet.

**Comment by tcstewar** [comment]
> Nice, but will there be a PyPI release soon? Otherwise, it won't help me a lot yet.

It's now released!  :)

**Comment by jgosmann** [comment]
Great, will test today and close issues if it works.
